apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: nginx
  namespace: testing
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx

  # will add this label app.kubernetes.io/instance: k-lab-uno